### PR TITLE
Create Italian translation

### PR DESCRIPTION
**Pull request by albanobattistella**

### CODE REVIEW

**Comment by ronniedroid** [comment]
Thank you :-)

**Comment by ronniedroid** [comment]
@albanobattistella What name should I use to credit you for the translation?

**Comment by albanobattistella** [comment]
HI,

Albano Battistella

Il giorno gio 29 ago 2024 alle ore 11:46 ***@***.*** <
***@***.***> ha scritto:

**Comment by ronniedroid** [comment]
Hey, sorry I didn't thought to look for your name at the top of the PO file, I did now. You will be correctly credited in the next release. 

There are a few new strings to translate if you'd like to do it :-)

**Pull request merged**
